### ISSUE TITLE
Have you tried CEM on soft actor critic alg? (SAC)

### ISSUE THREAD

**Issue by tldoan** [apourchot/EvoLearn#1]
Hi,

thanks for releasing your code ! 
Btw, have you by any chance tried implementing your CEM method on SAC algorithm?

thanks !

**Comment by apourchot** [comment]
Hi,
Thank you for your interest in the project :) I've been wanting to try this for a while now, but unfortunately I'm now busy with other projects, so I'm afraid that it'll have to wait...
Cheers

**Comment by tldoan** [comment]
Hey,

Yesterday , I your code CEM on SAC (I implemented CEM on top of a pytorch code of SAC I found ) and for Ant-v2 it plateau at 1000 while CEM -TD3 seems to provides good results. So problably while do the reverse (implementing sac from your code). 
Is there any parameters I should  carefully tune when putting CEM on SAC??? 

thanks again !

**Comment by apourchot** [comment]
Hi again,
The decay of the covariance for the CEM algorithm should be tuned carefully, but the one that I used for my experiments should work fine. Tell me if you get something interesting !
