### ISSUE TITLE
Code related issues

### ISSUE THREAD

**Issue by ZhenZhuHuang** [apourchot/EvoLearn#3]
`    def tell(self, solutions, scores):
        """
        Updates the distribution
        """
        scores = np.array(scores)
        scores *= -1

        idx_sorted = np.argsort(scores)

        old_mu = self.mu
        self.damp = self.damp * self.tau + (1 - self.tau) * self.damp_limit
        self.mu = self.weights @ solutions[idx_sorted[:self.parents]]

        z = (solutions[idx_sorted[:self.parents]] - old_mu)
        self.cov = 1 / self.parents * self.weights @ (
            z * z) + self.damp * np.ones(self.num_params)

        self.elite = solutions[idx_sorted[0]]
        self.elite_score = scores[idx_sorted[0]]
        print(self.cov)`
Hello, Sir, I found that your code at this point is in ascending order by default when sorting fitness. In this case, shouldn't Elite be last?

The np.argsort() function defaults to ascending sort.

**Comment by apourchot** [comment]
Hi, the scores are multiplied by -1 at the beginning of the method, so that the best original score becomes the lowest score at the time of the argsort. Hope this clarifies.

**Comment by ZhenZhuHuang** [comment]
Oh, I see, thank you!






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "apourchot/CEM-RL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月24日(星期二) 下午4:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [apourchot/CEM-RL] Code related issues (Issue #3)





 
Hi, the scores are multiplied by -1 at the beginning of the method, so that the best original score becomes the lowest score at the time of the argsort. Hope this clarifies.
